/**
 * Bookkeeping-frame filter (Phase 3e-polish, 2026-05-08).
 *
 * The hive-mind recall surface returns frames ranked by relevance. Some of
 * those frames are NOT user-stated content — they're auto-generated
 * bookkeeping that the synthesis pipeline and the hooks themselves produce.
 * In top-N relevance recall they look "related" because they're keyword-rich,
 * but they carry no real signal for in-loop enrichment.
 *
 * Three patterns:
 *   1. wiki-synth session summaries — `[wiki-synth task:... kind:...]`
 *      Generated by the synthesis pipeline. Third-person bookkeeping like
 *      "On 2026-05-05 the X pipeline reached operational stability."
 *      Almost never useful as recall context.
 *
 *   2. own user-prompt-submit traces — `[hm session:... event:user-prompt-submit ...]`
 *      The user's own prompts saved by THIS hook. Within the same session
 *      they're already in conversation context (redundant); cross-session
 *      they're better served by wiki-synth + last-activity. Cross-project
 *      they're noise.
 *
 *   3. own post-tool-use traces — `[hm session:... event:post-tool-use ...]`
 *      Tool-call bookkeeping. Same logic as #2 — the LLM recomputes anyway.
 *
 * Decision (Marko 2026-05-08): unified filter — exclude all three patterns
 * from EVERY downstream consumer (regular recall section, 3e-1 failure
 * detection, 3e-2 cross-project, 3e-4 contradiction detection). Continuity
 * across sessions comes from wiki-synth and the last-activity greeting; we
 * don't need raw prompt frames for that.
 */

const WIKI_SYNTH_RX = /^\[wiki-synth\s/;
const HM_TRACE_RX = /^\[hm\s+session:[^\]]*\bevent:(?:user-prompt-submit|post-tool-use)\b/;

/**
 * @param {string} content
 * @returns {boolean}
 */
export function isBookkeepingFrame(content) {
  if (typeof content !== 'string' || content.length === 0) return false;
  // Strip leading whitespace defensively — some frames have a stray space
  const c = content.replace(/^\s+/, '');
  return WIKI_SYNTH_RX.test(c) || HM_TRACE_RX.test(c);
}

/**
 * Convenience helper: filter a recall result list down to non-bookkeeping
 * frames in one call.
 *
 * @param {Array<{content?:string}>} recall
 * @returns {Array}
 */
export function dropBookkeeping(recall) {
  if (!Array.isArray(recall)) return [];
  return recall.filter((h) => !isBookkeepingFrame(h && h.content));
}
